### DISCUSSION TITLE
App - 'The data couldn't be read because it is missing'

### DISCUSSION THREAD

**Discussion by MrMeeb** [simple-login/app#1328] [Self-hosting question] [answered]
Hi all,

Following what I believe was the 2.0.0 update, lots of the functions no longer seem to work. I can login to my SL instance without issue, but when navigating to create an alias, or view account details I get the error 'The data couldn't be read because it is missing'. 

I am confident these issues didn't happen prior to this update

No errors in the docker logs, just an entry from sl-app and my nginx proxy when trying:

```
sl-app         | 2022-10-01 10:35:48,081 - SL - DEBUG - "/code/server.py:444" - after_request() -  - 172.23.0.6 GET /api/user_info ImmutableMultiDict([]) 200
sl-nginx       | [IP Redacted] - - [01/Oct/2022:10:35:48 +0000] "GET /api/user_info HTTP/1.1" 200 109 "-" "SimpleLogin/22102 CFNetwork/1335.0.3 Darwin/21.6.0" "-"
```

Steps to reproduce:

1. Open SimpleLogin app
2. Select My Account from the bottom row
3. Observe error

Trying to do either action via the web app or Chrome extension still works as expected. This is only limited to the mobile app

iOS Version 2.2.1 (Build 22102)

Tested on SimpleLogin v3.4.0 and 4.6.2-beta

Docker Compose file:

```
version: '3'

services:

  sl-postfix:
    image: git.mrmeeb.stream/mrmeeb/postfix:latest
    container_name: sl-postfix
    restart: unless-stopped
    networks:
      - simple-login
    depends_on:
      - "sl-db"
    ports:
      - "${SL_IP}:25:25"
    volumes:
      - ${DROOT}/postfix:/config
      - ${DROOT}/nginx/nginx_secrets:/etc/letsencrypt:ro

  sl-db:
    image: postgres:12.1
    container_name: sl-db
    restart: unless-stopped
    networks:
      - simple-login
    volumes:
      - ${DROOT}/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_USER=simplelogin
      - POSTGRES_DB=simplelogin

  sl-app:
    image: simplelogin/app:${SL_VERSION}
    container_name: sl-app
    restart: unless-stopped
    networks:
      - simple-login
    depends_on:
      - "sl-db"
    volumes:
      - ${DROOT}:/sl
      - ${DROOT}/upload:/code/static/upload
      - ${DROOT}/dkim.key:/dkim.key
      - ${DROOT}/dkim.pub.key:/dkim.pub.key
      - ${DROOT}/simplelogin.env:/code/.env

  sl-email:
    image: simplelogin/app:${SL_VERSION}
    container_name: sl-email
    restart: unless-stopped
    networks:
      - simple-login
    depends_on:
      - "sl-db"
    command: python email_handler.py
    volumes:
      - ${DROOT}:/sl
      - ${DROOT}/upload:/code/static/upload
      - ${DROOT}/dkim.key:/dkim.key
      - ${DROOT}/dkim.pub.key:/dkim.pub.key
      - ${DROOT}/simplelogin.env:/code/.env

  sl-job-runner:
    image: simplelogin/app:${SL_VERSION}
    container_name: sl-job-runner
    restart: unless-stopped
    networks:
      - simple-login
    depends_on:
      - "sl-db"
    command: python job_runner.py
    volumes:
      - ${DROOT}:/sl
      - ${DROOT}/upload:/code/static/upload
      - ${DROOT}/dkim.key:/dkim.key
      - ${DROOT}/dkim.pub.key:/dkim.pub.key
      - ${DROOT}/simplelogin.env:/code/.env

#  sl-migration:
#    image: simplelogin/app:${SL_VERSION}
#    container_name: sl-migration
#    restart: "no"
#    networks:
#      - simple-login
#    depends_on:
#      - "sl-db"
#    command: alembic upgrade head
#    volumes:
#      - ${DROOT}:/sl
#      - ${DROOT}/upload:/code/static/upload
#      - ${DROOT}/dkim.key:/dkim.key
#      - ${DROOT}/dkim.pub.key:/dkim.pub.key
#      - ${DROOT}/simplelogin.env:/code/.env

#  sl-init:
#    image: simplelogin/app:${SL_VERSION}
#    container_name: sl-init
#    restart: "no"
#    networks:
#      - simple-login
#    depends_on:
#      - "sl-db"
#    command: python init_app.py
#    volumes:
#      - ${DROOT}:/sl
#      - ${DROOT}/upload:/code/static/upload
#      - ${DROOT}/dkim.key:/dkim.key
#      - ${DROOT}/dkim.pub.key:/dkim.pub.key
#      - ${DROOT}/simplelogin.env:/code/.env


  sl-nginx:
    image: jonasal/nginx-certbot:latest
    container_name: sl-nginx
    restart: unless-stopped
    networks:
      - simple-login
    depends_on:
      - "sl-app"
    ports:
      - "${SL_IP}:80:80"
      - "${SL_IP}:443:443"
    volumes:
      - ${DROOT}/nginx/nginx_secrets:/etc/letsencrypt
      - ${DROOT}/nginx/user_conf.d:/etc/nginx/user_conf.d:ro
    env_file:
      - ${DROOT}/nginx/nginx-certbot.env

networks:
  simple-login:
    name: simple-login
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24

```
