### DISCUSSION TITLE
How to manually add a user?

### DISCUSSION THREAD

**Discussion by damien-crypto** [simple-login/app#448] [Self-hosting question]
How do I manually add a family member since i have registration turned off.
If I turn on registration and get a unwanted registration how would I see they registered and delete them?
Is there a administrator control panel?
Thank you for any response.
This is my first github post.

**Comment by nguyenkims** [comment]
Hi currently the admin UI isn't developed for managing the self-hosting instance but rather for us for handling billing related requests :). In the meantime, I suggest opening the registration shortly and if other people sign up, you can delete them via the database (the table `users`).

**Reply by damien-crypto** [reply]
Awesome thanks for the reply!

I can't figure it out yet.

Have a nice day :)

**Reply by FarisZR** [reply]
> Awesome thanks for the reply!
> 
> I can't figure it out yet.
> 
> Have a nice day :)

use something like pgadmin
it makes managing pgsql databases easier, also they have a docker image

**Reply by JReming85** [reply]
Can be done very easily by creating a docker-compose.yml

assuming you used all default settings spinning up SL, this would work perfectly

```
version: '3.8'

services:

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: myemail@fqdn.com
      PGADMIN_DEFAULT_PASSWORD: mysupersecretpassword
    ports:
      - "5050:80"

networks:
   default:
      external:
         name: sl-network
```

Make sure to change the admin login/password and when adding the simplelogin db, use `sl-db` as the hostname
