### DISCUSSION TITLE
Provide a way to change API nb_ data period

### DISCUSSION THREAD

**Discussion by EthraZa** [simple-login/app#684] [Feature Requests]
Right now, all the [nb_ data on the API](https://github.com/simple-login/app/blob/master/docs/api.md#get-apiv2aliases) are the sum of the last 14 days and are used to show stats on the UI (with exception of nb_aliases that is the sum of all aliases under that user).
If the nb_ data where telling about the current month, for example, it would be more easy to me to imagine uses for it.

- [x] nb_ feature request:
I would like to suggest 2 scenario options to enhance this data so it get useful for more people.

I'm guessing the scenario 1 (custom period) would be the easiest to implement maintaining backward compatibility.
But, scenarios 2.0 and 2.1 are for if, for some reason, to offer a custom period is out of possibility.

___
### 1. Custom period:
````php
GET /api/v2/aliases? nb_days=30  // If omitted, default is 14 
````
The resulting JSON would keep the same as the current one.

* The server implementation could have a limit cap for this one, or you could just set a generous enough hardcoded limit cap like 90 days.

___
### 2. Fixed periods:

Monthly data:
```yml
"month_current": {
    "nb_block": 0,
    "nb_forward": 1,
    "nb_reply": 0
},
"month_last": {
    "nb_block": 1,
    "nb_forward": 2,
    "nb_reply": 1
}
```
Alternative...

Monthly / Weekly data:
```yml
"month_current": {
    "nb_block": {
        "week_1": 0,
        "week_2": 2,
        "week_3": 4,
        "week_4": 1
    },
    "nb_forward": {..},
    "nb_reply": {..}
},
"month_last": {...}
```
