### ISSUE TITLE
Self host add subdomain manually. Can't restore deleted alias

### ISSUE THREAD

**Issue by whisperdancer** [simple-login/app#1492]
I'm self hosting 4.6.3. All is running great. I wanted to add my own domain as a custom domain, but am unable to do so within the app as I get an error. So I followed this thread

https://github.com/simple-login/app/issues/382

I added the record to the custom_domain table. The app then shows it. I verified the domain, then verified the mx records. Easy as the dns records were already in place since my public domain is the same as the custom domain.

To test, I create a new alias. Tested the send and receive and all works fine. I then delete the alias and verify by viewing it in the db. 

`select * from deleted_alias; `shows the deleted domain.

I then go to the domain details and select deleted domains and the deleted alias doesn't show. It says there are no deleted alias's. It seems as though SL is also looking at the public domain and does not detect that the deleted alias is actually a custom domain.

**Comment by zzahkaboom24** [comment]
Few years too late for you probably, but maybe helpful for anyone stumbling upon this.
I recently started self-hosting SimpleLogin too, and inevitably had to also use the workaround for my custom domain in #382.

Before adding aliases, here are the queries I used to remove my domain from the public domains:
```sql
-- Get the ID of your domain in the public_domain entry
SELECT id,domain FROM public_domain;

-- Delete your domain from the public_domain entry using the ID
DELETE FROM public_domain WHERE id = #YOUR_ID#;
```
If you already had trashed aliases, you can delete them in the following way:
```sql
-- Get the ID of your trashed aliases
SELECT id,email FROM deleted_alias;

-- Delete either 1 alias you wish, or all at once
-- Deleting one
DELETE FROM deleted_alias WHERE id = #YOUR_ID#;
-- Deleting all
DELETE FROM deleted_alias;
```
Then refer back to the first codeblock.

Deleting an alias then should finally make it visible inside SimpleLogin -> `Domains` -> `Details ➡` -> `Deleted Alias`, because your custom domain is not in both the public_domain and custom_domain entry no more.

I hope this helps someone out.

**Comment by whisperdancer** [comment]
Hi, this is great if it's what I think it is. Thanks for sharing. Does doing this finally mean I can restore a previously deleted domain from within simploglogin? Thanks

**Comment by zzahkaboom24** [comment]
> Hi, this is great if it's what I think it is. Thanks for sharing. Does doing this finally mean I can restore a previously deleted domain from within simploglogin? Thanks

Yes, I stated this in my second-last sentence:

> Deleting an alias then should finally make it visible inside SimpleLogin -> Domains -> Details ➡ -> Deleted Alias, because your custom domain is not in both the public_domain and custom_domain entry.

**Comment by whisperdancer** [comment]
This is working great. Thanks so much for sharing 👍 

Unsure how you setup your simplelogin. I initially set it up according to the guide from simplelogin. Very time consuming and overly complex and installs postfix on the host. I also don't like using docker run commands and prefer a complete docker solution using docker compose. The dev team at simplelogin have for a long time talked about offering a docker compose solution, but I don't think they ever found the time. I recently discovered this fantastic guide, dumped the old way and redeployed using this guide. As the DNS stuff was already done, this just took a fraction of the time to deploy and worked perfect first time out of the box. Swag handles all the certs and has built in fail2ban IPS protection.

Just thought I'd share if it helps. 

https://virtualize.link/Containers/simplelogin/

**Comment by zzahkaboom24** [comment]
I made my own docker compose:

```
volumes:
  simplelogin-postgres_data:
    name: simplelogin-postgres_data
  simplelogin_data:
    name: simplelogin_data
  simplelogin-pgp_data:
    name: simplelogin-pgp_data
  simplelogin-upload_data:
    name: simplelogin-upload_data
  simplelogin-postfix_data:
    name: simplelogin-postfix_data
  simplelogin-letsencrypt_data:
    name: simplelogin-letsencrypt_data

services:
    simpleloginpostgres:
        image: postgres:12.1
        container_name: SimpleLoginPostgres
        env_file: stack.env
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} && psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1'"]
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 30s
        volumes:
            - simplelogin-postgres_data:/var/lib/postgresql/data
        restart: always
        networks:
            - nginxproxymanager_default

    simpleloginmigration:
        image: simplelogin/app-ci:master
        container_name: SimpleLoginMigration
        env_file: stack.env
        environment:
            - URL=https://redacted
            - EMAIL_DOMAIN=redacted
            - SUPPORT_EMAIL=support@redacted
            - EMAIL_SERVERS_WITH_PRIORITY=[(10, "redacted.")]
            - DISABLE_ALIAS_SUFFIX=1
            - DB_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@simpleloginpostgres:5432/${POSTGRES_DB}
            - GNUPGHOME=/sl/pgp
            - LOCAL_FILE_UPLOAD=1
            - POSTFIX_SERVER=simpleloginpostfix
            - DKIM_PRIVATE_KEY_PATH=/dkim.key
            - FLASK_SECRET=${FLASK_SECRET}
        volumes:
            - simplelogin_data:/sl
            - simplelogin-pgp_data:/sl/pgp
            - simplelogin-upload_data:/code/static/upload
            - /home/zzahkaboom24/Files/SimpleLogin/dkim.key:/dkim.key
        depends_on:
            simpleloginpostgres:
                condition: service_healthy
        command: alembic upgrade head
        networks:
            - nginxproxymanager_default

    simplelogininit:
        image: simplelogin/app-ci:master
        container_name: SimpleLoginInit
        env_file: stack.env
        environment:
            - URL=https://redacted
            - EMAIL_DOMAIN=redacted
            - SUPPORT_EMAIL=support@redacted
            - EMAIL_SERVERS_WITH_PRIORITY=[(10, "redacted.")]
            - DISABLE_ALIAS_SUFFIX=1
            - DB_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@simpleloginpostgres:5432/${POSTGRES_DB}
            - GNUPGHOME=/sl/pgp
            - LOCAL_FILE_UPLOAD=1
            - POSTFIX_SERVER=simpleloginpostfix
            - DKIM_PRIVATE_KEY_PATH=/dkim.key
            - FLASK_SECRET=${FLASK_SECRET}
        volumes:
            - simplelogin_data:/sl
            - simplelogin-pgp_data:/sl/pgp
            - /home/zzahkaboom24/Files/SimpleLogin/dkim.key:/dkim.key
        depends_on:
            simpleloginmigration:
                condition: service_completed_successfully
        command: python init_app.py
        networks:
            - nginxproxymanager_default

    simpleloginapp:
        image: simplelogin/app-ci:master
        container_name: SimpleLoginApp
        env_file: stack.env
        environment:
            - URL=https://redacted
            - EMAIL_DOMAIN=redacted
            - SUPPORT_EMAIL=support@redacted
            - EMAIL_SERVERS_WITH_PRIORITY=[(10, "redacted.")]
            - DISABLE_ALIAS_SUFFIX=1
            - DB_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@simpleloginpostgres:5432/${POSTGRES_DB}
            - GNUPGHOME=/sl/pgp
            - LOCAL_FILE_UPLOAD=1
            - POSTFIX_SERVER=simpleloginpostfix
            - DKIM_PRIVATE_KEY_PATH=/dkim.key
            - FLASK_SECRET=${FLASK_SECRET}
            # Comment the two environment variables below to enable registration; Uncomment to disable registration.
            # - DISABLE_REGISTRATION=1
            # - DISABLE_ONBOARDING=true
        volumes:
            - simplelogin_data:/sl
            - simplelogin-upload_data:/code/static/upload
            - /home/zzahkaboom24/Files/SimpleLogin/dkim.key:/dkim.key
        ports:
            - 7777:7777
        depends_on:
            simplelogininit:
                condition: service_completed_successfully
        restart: always
        command: ["gunicorn","wsgi:app","-b","0.0.0.0:7777","-w","2","--timeout","60"]
        networks:
            - nginxproxymanager_default

    simpleloginemail:
        image: simplelogin/app-ci:master
        container_name: SimpleLoginEMail
        env_file: stack.env
        environment:
            - URL=https://redacted
            - EMAIL_DOMAIN=redacted
            - SUPPORT_EMAIL=support@redacted
            - EMAIL_SERVERS_WITH_PRIORITY=[(10, "redacted.")]
            - DISABLE_ALIAS_SUFFIX=1
            - DB_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@simpleloginpostgres:5432/${POSTGRES_DB}
            - GNUPGHOME=/sl/pgp
            - LOCAL_FILE_UPLOAD=1
            - POSTFIX_SERVER=simpleloginpostfix
            - DKIM_PRIVATE_KEY_PATH=/dkim.key
            - FLASK_SECRET=${FLASK_SECRET}
        volumes:
            - simplelogin_data:/sl
            - simplelogin-upload_data:/code/static/upload
            - /home/zzahkaboom24/Files/SimpleLogin/dkim.key:/dkim.key
        ports:
            - 20381:20381
        depends_on:
            simplelogininit:
                condition: service_completed_successfully
        restart: always
        command: python email_handler.py
        networks:
            - nginxproxymanager_default

    simpleloginjobrunner:
        image: simplelogin/app-ci:master
        container_name: SimpleLoginJobRunner
        env_file: stack.env
        environment:
            - URL=https://redacted
            - EMAIL_DOMAIN=redacted
            - SUPPORT_EMAIL=support@redacted
            - EMAIL_SERVERS_WITH_PRIORITY=[(10, "redacted.")]
            - DISABLE_ALIAS_SUFFIX=1
            - DB_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@simpleloginpostgres:5432/${POSTGRES_DB}
            - GNUPGHOME=/sl/pgp
            - LOCAL_FILE_UPLOAD=1
            - POSTFIX_SERVER=simpleloginpostfix
            - DKIM_PRIVATE_KEY_PATH=/dkim.key
            - FLASK_SECRET=${FLASK_SECRET}
        volumes:
            - simplelogin_data:/sl
            - simplelogin-upload_data:/code/static/upload
            - /home/zzahkaboom24/Files/SimpleLogin/dkim.key:/dkim.key
        depends_on:
            simplelogininit:
                condition: service_completed_successfully
        restart: always
        command: python job_runner.py
        networks:
            - nginxproxymanager_default

    simpleloginpostfix:
        image: simplelogin/postfix:sha-a683dce
        container_name: SimpleLoginPostfix
        command: >
            bash -c "
            sed -i '/_main \"\\$@\"/i sed -i \"\\/# TLS parameters for SMPTD (incoming mail)\\/{n;s\\/smtp_tls_security_level\\/smtpd_tls_security_level\\/}\" /etc/postfix/main.cf\\npostfix start-fg' /src/docker-entrypoint.sh &&
            sed -i 's/&& postfix start-fg//' /src/docker-entrypoint.sh &&
            /src/docker-entrypoint.sh
            "
        env_file: stack.env
        environment:
            - ALIASES_DEFAULT_DOMAIN=redacted
            - DB_HOST=simpleloginpostgres
            - DB_USER=${POSTGRES_USER}
            - DB_PASSWORD=${POSTGRES_PASSWORD}
            - DB_NAME=${POSTGRES_DB}
            - EMAIL_HANDLER_HOST=simpleloginemail
            - LETSENCRYPT_EMAIL=redacted@gmail.com
            - POSTFIX_FQDN=redacted
            - SIMPLELOGIN_COMPATIBILITY_MODE=v4
            - RELAY_HOST=${RELAY_HOST}
            - RELAY_PORT=${RELAY_PORT}
            - RELAY_HOST_USERNAME=${RELAY_HOST_USERNAME}
            - RELAY_HOST_PASSWORD=${RELAY_HOST_PASSWORD}
        dns:
            - 8.8.8.8
            - 8.8.4.4
        volumes:
            - simplelogin-postfix_data:/etc/postfix
            - simplelogin-letsencrypt_data:/etc/letsencrypt
        ports:
            - 25:25
            - 587:587
        depends_on:
            simplelogininit:
                condition: service_completed_successfully
        restart: always
        networks:
            - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true
    name: nginxproxymanager_default
```

**Comment by zzahkaboom24** [comment]
Just to make one thing clear about my docker compose;
Having the same environment variables across 5 different Docker containers was not entirely my idea.
I just kept it that way because the readme showed it like that

<img width="941" height="830" alt="Image" src="https://github.com/user-attachments/assets/bf220bd3-7d15-4ae1-883f-03c44e741fa2" />

**Comment by zzahkaboom24** [comment]
Additionally, the super complex command for the postfix docker container I only made to fix the typo that exact docker container had.
With that being said, I am a sucker for volumes and would put my entire life into volumes

**Comment by whisperdancer** [comment]
Glad you got it working with compose also. 👍

**Comment by whisperdancer** [comment]
so nginxproxymanager handles your certs similar to swag in the guide I posted?

**Comment by zzahkaboom24** [comment]
Maybe I could simplify it into one singular docker container instead of 5 by running each necessary command one after the other.
I am bored now so I guess I'll do it now

**Comment by zzahkaboom24** [comment]
> so nginxproxymanager handles your certs similar to swag in the guide I posted?

Yes

**Comment by whisperdancer** [comment]
I love the simplicity of the swag guide. They encapsulated much of the simplelogin complexity in their simplelogin container. You can see it in the logs when run first time.

**Comment by whisperdancer** [comment]
I also like the way they set up the self test so one is notified of email delivery issues

**Comment by whisperdancer** [comment]
I also keep hoping they will offer an update as 4.6.5 beta has been out for years. It works, but would love some of the new features in the self-hosted version.

**Comment by zzahkaboom24** [comment]
I am running latest.
And with latest I mean latest, not 4.6.5 beta

**Comment by zzahkaboom24** [comment]
I am currently slightly rewriting the docker compose of mine for more simplicity (and would make my life easier not having to copy paste 5 times)

**Comment by whisperdancer** [comment]
Oh, my understanding is latest self host version available is 4.6.5 beta?

**Comment by zzahkaboom24** [comment]
> Oh, my understanding is latest self host version available is 4.6.5 beta?

When you checked my docker compose, I hope you saw that as the image, I used simplelogin/app-ci:master

**Comment by zzahkaboom24** [comment]
This is my new docker compose, I tried simplifying as much as possible including the typo fix for postfix.

```
volumes:
  simplelogin-postgres_data:
    name: simplelogin-postgres_data
  simplelogin_data:
    name: simplelogin_data
  simplelogin-pgp_data:
    name: simplelogin-pgp_data
  simplelogin-upload_data:
    name: simplelogin-upload_data
  simplelogin-postfix_data:
    name: simplelogin-postfix_data
  simplelogin-letsencrypt_data:
    name: simplelogin-letsencrypt_data

services:
    simpleloginpostgres:
        image: postgres:12.1
        container_name: SimpleLoginPostgres
        env_file: stack.env
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} && psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1'"]
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 30s
        volumes:
            - simplelogin-postgres_data:/var/lib/postgresql/data
        restart: always
        networks:
            - nginxproxymanager_default

    simplelogin:
        image: simplelogin/app-ci:master
        container_name: SimpleLogin
        env_file: stack.env
        environment:
            - URL=https://redacted
            - EMAIL_DOMAIN=redacted
            - SUPPORT_EMAIL=support@redacted
            - EMAIL_SERVERS_WITH_PRIORITY=[(10, "redacted.")]
            - DISABLE_ALIAS_SUFFIX=1
            - DB_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@simpleloginpostgres:5432/${POSTGRES_DB}
            - GNUPGHOME=/sl/pgp
            - LOCAL_FILE_UPLOAD=1
            - POSTFIX_SERVER=simpleloginpostfix
            - DKIM_PRIVATE_KEY_PATH=/dkim.key
            - FLASK_SECRET=${FLASK_SECRET}
            # Comment the two environment variables below to enable registration; Uncomment to disable registration.
            # - DISABLE_REGISTRATION=1
            # - DISABLE_ONBOARDING=true
        volumes:
            - simplelogin_data:/sl
            - simplelogin-pgp_data:/sl/pgp
            - simplelogin-upload_data:/code/static/upload
            - /home/zzahkaboom24/Files/SimpleLogin/dkim.key:/dkim.key
        ports:
            - 7777:7777
            - 20381:20381
        depends_on:
            simpleloginpostgres:
                condition: service_healthy
        restart: always
        command: >
          bash -c "
            alembic upgrade head > /sl/migration.log 2>&1 &&
            python init_app.py > /sl/init.log 2>&1 &&
            python job_runner.py > /sl/job_runner.log 2>&1 & 
            python email_handler.py > /sl/email_handler.log 2>&1 &
            gunicorn wsgi:app -b 0.0.0.0:7777 -w 2 --timeout 60
            "       
        networks:
            - nginxproxymanager_default

    simpleloginpostfix:
        image: simplelogin/postfix:sha-a683dce
        container_name: SimpleLoginPostfix
        entrypoint: bash
        command:
          - -c
          - |
            /src/docker-entrypoint.sh &
            while ! netstat -tnl | grep -q ':25'; do sleep 1; done
            sed -i '/# TLS parameters for SMPTD (incoming mail)/{n;s/smtp_tls_security_level/smtpd_tls_security_level/}' /etc/postfix/main.cf
            postfix reload
            wait
        env_file: stack.env
        environment:
            - ALIASES_DEFAULT_DOMAIN=redacted
            - DB_HOST=simpleloginpostgres
            - DB_USER=${POSTGRES_USER}
            - DB_PASSWORD=${POSTGRES_PASSWORD}
            - DB_NAME=${POSTGRES_DB}
            - EMAIL_HANDLER_HOST=simplelogin
            - LETSENCRYPT_EMAIL=redacted@gmail.com
            - POSTFIX_FQDN=redacted
            - SIMPLELOGIN_COMPATIBILITY_MODE=v4
            - RELAY_HOST=${RELAY_HOST}
            - RELAY_PORT=${RELAY_PORT}
            - RELAY_HOST_USERNAME=${RELAY_HOST_USERNAME}
            - RELAY_HOST_PASSWORD=${RELAY_HOST_PASSWORD}
        dns:
            - 8.8.8.8
            - 8.8.4.4
        volumes:
            - simplelogin-postfix_data:/etc/postfix
            - simplelogin-letsencrypt_data:/etc/letsencrypt
        ports:
            - 25:25
            - 587:587
        depends_on:
            simplelogin:
                condition: service_started
        restart: always
        networks:
            - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true
    name: nginxproxymanager_default
```

**Comment by zzahkaboom24** [comment]
I'll daily drive this and see if it works as it should or nah

**Comment by zzahkaboom24** [comment]
My [fix](https://github.com/simple-login/app/issues/1492#issuecomment-3077683786) still works using my new shortened docker compose and so does everything else.
I will use it like that :)

**Comment by whisperdancer** [comment]
What version are you running?

**Comment by zzahkaboom24** [comment]
> What version are you running?

simplelogin/app-ci:master is what I am running.
Technically no version number is shown [because I have not used v4.68.5 in my docker compose, thinking master would keep me on latest, no matter if breaking changes or nah], but it's nothing we can't "fix".
By comparing the sha256 -> sha256:baee541c116f704d351a26292d6eb4f69b07dfcbc566905e1269e45042006b63 with the available [tags](https://hub.docker.com/r/simplelogin/app-ci/tags), I can relatively quickly see that I do, in fact, have "master".
Just click on the master tag, and right next to the SimpleLogin logo one will be able to see `Index digest sha256:baee541c116f704d351a26292d6eb4f69b07dfcbc566905e1269e45042006b63`, which matches what I have locally downloaded.
And "master" came out the most recent/30 days ago.

These are the commands + outputs I used:
```
zzahkaboom24@Ubuntu-2404-noble-amd64-base:~$ docker images | grep simplelogin
simplelogin/app-ci            master        dafbf693b46a   4 weeks ago     1.08GB
simplelogin/postfix           sha-a683dce   77055bb8d62e   9 months ago    86.7MB
```
```
zzahkaboom24@Ubuntu-2404-noble-amd64-base:~$ docker inspect dafbf693b46a | grep -A 1 RepoDigests
        "RepoDigests": [
            "simplelogin/app-ci@sha256:baee541c116f704d351a26292d6eb4f69b07dfcbc566905e1269e45042006b63"
```

**Comment by zzahkaboom24** [comment]
Final change to my docker compose, added support for customizing the postgres port, if one needs that.
I will run SimpleLogin this way from now on, and I do not think that further changes to my Docker Compose are necessary anymore:
```
volumes:
  simplelogin-postgres_data:
    name: simplelogin-postgres_data
  simplelogin_data:
    name: simplelogin_data
  simplelogin-pgp_data:
    name: simplelogin-pgp_data
  simplelogin-upload_data:
    name: simplelogin-upload_data
  simplelogin-postfix_data:
    name: simplelogin-postfix_data
  simplelogin-letsencrypt_data:
    name: simplelogin-letsencrypt_data

services:
    simpleloginpostgres:
        image: postgres:12.1
        container_name: SimpleLoginPostgres
        entrypoint: bash
        command:
          - -c
          - |
            /docker-entrypoint.sh postgres -c port=${POSTGRES_PORT} &
            until pg_isready -U ${POSTGRES_USER} -p ${POSTGRES_PORT} >/dev/null 2>&1; do
              sleep 10
            done
            psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT} -c "
              DO \$$outer\$$
              BEGIN
                  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'public_domain') THEN
                      DROP TRIGGER IF EXISTS clear_public_domain_trigger ON public_domain;
                      CREATE OR REPLACE FUNCTION clear_public_domain()
                      RETURNS TRIGGER AS \$$func\$$
                      BEGIN
                          DELETE FROM public_domain;
                          RETURN NULL;
                      END;
                      \$$func\$$ LANGUAGE plpgsql;
                      CREATE TRIGGER clear_public_domain_trigger
                      AFTER INSERT ON public_domain
                      FOR EACH STATEMENT
                      EXECUTE FUNCTION clear_public_domain();
                      DELETE FROM public_domain;
                  END IF;
              END
              \$$outer\$$;
            "
            wait
        env_file: .env
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} -p $${POSTGRES_PORT} && psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p $${POSTGRES_PORT} -c 'SELECT 1'"]
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 30s
        volumes:
            - simplelogin-postgres_data:/var/lib/postgresql/data
        ports:
            - 5433:5433
        restart: always
        networks:
            - simplelogin-network

    simplelogin:
        image: simplelogin/app-ci:master
        container_name: SimpleLogin
        env_file: .env
        environment:
            - URL=https://app.example.tld
            - EMAIL_DOMAIN=example.tld
            - OTHER_ALIAS_DOMAINS=["example2.tld, example3.tld"]
            - FIRST_ALIAS_DOMAIN=example.tld
            - ALIAS_LIMIT="9999/minute"
            - SUPPORT_EMAIL=support@example.tld
            - EMAIL_SERVERS_WITH_PRIORITY=[(10, "app.example.tld.")]
            - DISABLE_ALIAS_SUFFIX=1
            - DB_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@simpleloginpostgres:${POSTGRES_PORT}/${POSTGRES_DB}
            - GNUPGHOME=/sl/pgp
            - LOCAL_FILE_UPLOAD=1
            - POSTFIX_SERVER=simpleloginpostfix
            - DKIM_PRIVATE_KEY_PATH=/dkim.key
            - FLASK_SECRET=${FLASK_SECRET}
            # Comment the two environment variables below to enable registration; Uncomment to disable registration.
            - DISABLE_REGISTRATION=1
            - DISABLE_ONBOARDING=true
        volumes:
            - simplelogin_data:/sl
            - simplelogin-pgp_data:/sl/pgp
            - simplelogin-upload_data:/code/static/upload
            - /root/dkim.key:/dkim.key
        ports:
            - 7777:7777
            - 20381:20381
        depends_on:
            simpleloginpostgres:
                condition: service_healthy
        restart: always
        command: >
          bash -c "
            alembic upgrade head > /sl/migration.log 2>&1 &&
            python init_app.py > /sl/init.log 2>&1 &&
            python job_runner.py > /sl/job_runner.log 2>&1 & 
            python email_handler.py > /sl/email_handler.log 2>&1 &
            gunicorn wsgi:app -b 0.0.0.0:7777 -w 2 --timeout 60
            "
        networks:
            - simplelogin-network

    simpleloginpostfix:
        image: simplelogin/postfix:latest
        container_name: SimpleLoginPostfix
        entrypoint: sh
        command:
            - -c
            - |
              touch /disable.pem &&
              exec ./docker-entrypoint.sh
        env_file: .env
        environment:
            - ALIASES_DEFAULT_DOMAIN=example.tld
            - DB_HOST=simpleloginpostgres:${POSTGRES_PORT}
            - DB_USER=${POSTGRES_USER}
            - DB_PASSWORD=${POSTGRES_PASSWORD}
            - DB_NAME=${POSTGRES_DB}
            - EMAIL_HANDLER_HOST=simplelogin
            - LETSENCRYPT_EMAIL=email@example.tld
            - POSTFIX_FQDN=app.example.tld
            - POSTFIX_DQN_KEY=${POSTFIX_DQN_KEY}
            - SIMPLELOGIN_COMPATIBILITY_MODE=v4
            - RELAY_HOST=${RELAY_HOST}
            - RELAY_PORT=${RELAY_PORT}
            - RELAY_HOST_USERNAME=${RELAY_HOST_USERNAME}
            - RELAY_HOST_PASSWORD=${RELAY_HOST_PASSWORD}
            - TLS_KEY_FILE=${TLS_KEY_FILE}
            - TLS_CERT_FILE=${TLS_CERT_FILE}
        dns:
            - 8.8.8.8
            - 8.8.4.4
        volumes:
            - simplelogin-postfix_data:/etc/postfix
            - simplelogin-letsencrypt_data:/etc/letsencrypt
        ports:
            - 25:25
            - 587:587
        depends_on:
            simplelogin:
                condition: service_started
        restart: always
        networks:
            - simplelogin-network

networks:
  simplelogin-network:
    external: true
    name: simplelogin-network
```

Connecting to the Postgres database to fix issues, such as in #382 does not work anymore using `psql -U <myuser> -d simplelogin` if the port is something other than 5432.
Instead, one can use `psql -p <port> -U <myuser> -d simplelogin` which is equally easy.
For me, this is now closed as completed. It was nice and is nice to have it working that well.
Have a great day
