### ISSUE TITLE
Upgrade to v4.66.1 kills app

### ISSUE THREAD

**Issue by TheCableGuy99** [simple-login/app#2409]
Please note that this is only for bug report.

## Bug report
Cannot access web interface after upgrading, tried twice now.

**Describe the bug**
Whenever I upgrade to v4.66.1 I cannot access the web interface, and the browser extension isn't connecting either.

**Expected behavior**
To work as normal, everything works prior to the upgrade and it's happened twice now.

**Environment (If applicable):**
 - Windows 11 Pro
 - Edge with extension

**Additional context**
Please see attached logs which might provide some insight to the issue?

[sl_app.txt](https://github.com/user-attachments/files/19094483/sl_app.txt)
[sl_db.txt](https://github.com/user-attachments/files/19094482/sl_db.txt)
[sl_email.txt](https://github.com/user-attachments/files/19094480/sl_email.txt)
[sl_job-runner.txt](https://github.com/user-attachments/files/19094481/sl_job-runner.txt)

**Comment by martadams89** [comment]
Are you upgrading your database by running `alembic upgrade head` and then `python init_app.py`?

**Comment by martadams89** [comment]
Try saving this script and adjusting where necessary
```#!/bin/bash

# Define variables
APP_PATH="/home/youruser/simple-login"
MIGRATION_IMAGE="martadams89/sl-app:master"
NETWORK="yournetwork"

# Function to stop and remove containers
stop_and_remove_containers() {
    local containers=("sl-app" "sl-email" "sl-job-runner")
    for container in "${containers[@]}"; do
        if docker ps -a --format "{{.Names}}" | grep -q "$container"; then
            echo "Stopping container: $container"
            docker stop "$container"
            echo "Removing container: $container"
            docker rm "$container"
        else
            echo "Container $container does not exist or is not running."
        fi
    done
}

# Function to run container updates
run_updates() {
    echo "Running container update..."
    cd "$APP_PATH" || exit 1
    docker compose pull
}

# Function to run migration container
run_migration() {
    echo "Running migration container..."
    cd "$APP_PATH" || exit 1
    docker run --rm \
        --name sl-migration \
        -v "$(pwd)/sl:/sl" \
        -v "$(pwd)/sl/upload:/code/static/upload" \
        -v "$(pwd)/dkim.key:/dkim.key" \
        -v "$(pwd)/dkim.pub.key:/dkim.pub.key" \
        -v "$(pwd)/simplelogin.env:/code/.env" \
        --network="$NETWORK" \
        "$MIGRATION_IMAGE" alembic upgrade head
}

# Function to run initialization container
run_initialization() {
    echo "Running initialization container..."
    cd "$APP_PATH" || exit 1
    docker run --rm \
        --name sl-init \
        -v "$(pwd)/sl:/sl" \
        -v "$(pwd)/sl/upload:/code/static/upload" \
        -v "$(pwd)/dkim.key:/dkim.key" \
        -v "$(pwd)/dkim.pub.key:/dkim.pub.key" \
        -v "$(pwd)/simplelogin.env:/code/.env" \
        --network="$NETWORK" \
        "$MIGRATION_IMAGE" python init_app.py
}

# Function to bring up the application using docker-compose
start_containers() {
    echo "Starting containers using docker-compose..."
    cd "$APP_PATH" || exit 1
    docker compose up -d
}

# Main script
echo "Starting script execution..."

# Stop and remove old containers
stop_and_remove_containers

# Run container updates
run_updates

# Run migration
run_migration

# Run initialization
run_initialization

# Ensure all temporary containers are stopped
stop_and_remove_containers

# Start the application using docker-compose
start_containers

echo "Script execution completed."
```

Run that and it should bring up the containers, migrate the database, and then bring up the containers

**Comment by martadams89** [comment]
`APP_PATH=` is where your docker compose file is.

`martadams89/sl-app:master` is my fork of the repo that builds arm64 images, keep to `simplelogin/app-ci:latest` if you don't need arm.

`NETWORK=` is the name of the docker network used for your containers.

> I should run this script from anywhere on the server hosting the Docker containers, not inside the containers themselves, correct?
Yes, run where your containers are, ideally where your docker compose is (if you have one).

> Nothing else in the script needs changing—have I missed anything?
Should be good to go.

> Once this is set up, can I simply run this script in the future to perform a proper upgrade?
Yes! It should juts pull the latest container

FWIW here's my docker-compose file - again I'm using my own image as I'm running on arm64 for now
```
version: '3.3'
networks:
  default:
    external:
      name: traefik-public
services:
  postgres:
    image: postgres:12.1
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    container_name: sl-db
    ports:
      - "5432:5432"
    volumes:
      - ./sl/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=simplelogin
      - POSTGRES_PASSWORD=xxxx
      - POSTGRES_DB=simplelogin
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "diun.enable=true"

  certgen:
    container_name: sl-certgen
    image: martadams89/ssl-certs-generator:master
    environment:
      - SSL_KEY=privkey.pem
      - SSL_CERT=fullchain.pem
      - SSL_SUBJECT=mydomain.org
      - SSL_DNS=postfix.mydomain.org
      - CA_SUBJECT=docker-ca
    volumes:
      - ./postfix/certs:/certs
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  postfix:
    image: simplelogin/postfix:master
    container_name: sl-postfix
    ports:
      - "25:25"
    environment:
      - POSTFIX_FQDN=postfix.mydomain.org
      - ALIASES_DEFAULT_DOMAIN=mydomain.org
      - DB_NAME=simplelogin
      - DB_HOST=sl-db
      - DB_USER=simplelogin
      - DB_PASSWORD=xxxxx
      - TLS_KEY_FILE=/certs/privkey.pem
      - TLS_CERT_FILE=/certs/fullchain.pem
      - RELAY_HOST=smtp-relay.gmail.com
      - RELAY_PORT=25
      - RELAY_HOST_USERNAME=xxx@mydomain.co.uk
      - RELAY_HOST_PASSWORD=xxxx
      - POSTFIX_DQN_KEY=xxx
      #- ENABLE_PROXY_PROTOCOL=true
      - EMAIL_HANDLER_HOST=sl-email # Must be identical to the service name
      - SIMPLELOGIN_COMPATIBILITY_MODE=v4
    restart: always
    volumes:
      - ./postfix/certs:/certs
      - ./postfix/custom-data:/etc/postfix/custom-data
    labels:
     # - "com.centurylinklabs.watchtower.enable=true"
      - "diun.enable=true"

  spamassassin-app:
    image: tiredofit/spamassassin:latest
    container_name: sl-spamassassin
    ports:
      - 783:783
    volumes:
      - ./spamassassin/logs/spamassassin:/logs
      - ./spamassassin/conf:/config
      - ./spamassassin/data:/data
    environment:
      - TIMEZONE=Europe/London
      - CONTAINER_NAME=spamassassin-app
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "diun.enable=true"

  sl-app:
    image: martadams89/sl-app:master
    container_name: sl-app
    depends_on:
      - postgres
    ports:
      - "7777:7777"
    volumes:
      - ./sl:/sl
      - ./sl/upload:/code/static/upload
      - ./simplelogin.env:/code/.env
      - ./dkim.key:/dkim.key:ro
      - ./dkim.pub.key:/dkim.pub.key:ro
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.simplelogin.entrypoints=https"
      - "traefik.http.routers.simplelogin.rule=Host(`simplelogin.mydomain.co.uk`) || Host(`mydomain.org`) || Host(`www.mydomain.org`) || Host(`simplelogin.mydomain.org`)"
      - "traefik.http.services.simplelogin.loadbalancer.server.port=7777"
      - "traefik.http.routers.simplelogin.service=simplelogin"
      - "traefik.http.routers.simplelogin.tls=true"
     # simplelogin redirect
      - "traefik.http.routers.simplelogin.middlewares=simplelogin-redirect"
      - "traefik.http.middlewares.simplelogin-redirect.redirectregex.regex=^https:\\/\\/(?:simplelogin\\.mydomain\\.co\\.uk|www\\.mydomain\\.org|mydomain\\.org)/(.*)"
      - "traefik.http.middlewares.simplelogin-redirect.redirectregex.replacement=https://simplelogin.mydomain.org/$${1}"
      - "traefik.http.middlewares.simplelogin-redirect.redirectregex.permanent=true"

  sl-email:
    image: martadams89/sl-app:master
    container_name: sl-email
    command: python email_handler.py
    depends_on:
      - postgres
      - sl-app
    ports:
      - "20381:20381"
    volumes:
      - ./sl:/sl
      - ./sl/upload:/code/static/upload
      - ./simplelogin.env:/code/.env
      - ./dkim.key:/dkim.key:ro
      - ./dkim.pub.key:/dkim.pub.key:ro
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "diun.enable=true"

  sl-job-runner:
    image: martadams89/sl-app:master
    container_name: sl-job-runner
    command: python job_runner.py
    depends_on:
      - postgres
      - sl-app
      - sl-email
    volumes:
      - ./sl:/sl
      - ./sl/upload:/code/static/upload
      - ./simplelogin.env:/code/.env
      - ./dkim.key:/dkim.key:ro
      - ./dkim.pub.key:/dkim.pub.key:ro
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "diun.enable=true"
```
