### ISSUE TITLE
Unable to init data (simplelogin/app:3.3.0 python init_app.py)

### ISSUE THREAD

**Issue by rajaseg** [simple-login/app#422]
Thank you very much for the project. I am trying to run Simple Login in docker compose. I followed https://github.com/simple-login/app/pull/309/files 

But getting below error for init container.

```
>>> URL: http://app.mydomain.com
Paddle param not set
Upload files to local dir
>>> init logging <<<
2021-03-29 17:54:17,444 - sl - DEBUG - 9 - utils:11 - <module> - load words file: /code/local_data/words_alpha.txt
```
Here is my docker compose
```
version: "3.7"

services:
  sl-postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - sl-network
    volumes:
      - ./sldb:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=somethingspecialhere
      - POSTGRES_USER=postgres
      - POSTGRES_DB=simplelogin
  
  sl-init:
    image: simplelogin/app:3.2.2
    restart: unless-stopped
    depends_on:
      - sl-postgres
    command: python init_app.py
    networks:
      - sl-network
    volumes:
      - ./sl:/sl
      - ./slupload:/code/static/upload
      - ./simplelogin.env:/code/.env
      - ./dkim.key:/dkim.key
      - ./dkim.pub.key:/dkim.pub.key
    
  sl-app:
    image: simplelogin/app:3.2.2
    restart: unless-stopped
    depends_on:
      - sl-postgres
      - sl-email
    ports:
      - "7777:7777"
    networks:
      - sl-network
    volumes:
      - ./sl:/sl
      - ./slupload:/code/static/upload
      - ./simplelogin.env:/code/.env
      - ./dkim.key:/dkim.key
      - ./dkim.pub.key:/dkim.pub.key

  sl-email:
    image: simplelogin/app:3.2.2
    restart: unless-stopped
    depends_on:
      - sl-postgres
    command: python email_handler.py
    ports:
      - "20381:20381"
    networks:
      - sl-network
    volumes:
      - ./sl:/sl
      - ./slupload:/code/static/upload
      - ./simplelogin.env:/code/.env
      - ./dkim.key:/dkim.key
      - ./dkim.pub.key:/dkim.pub.key
volumes:
  sl:
  sldb:
  slupload:
networks:
  sl-network:
    driver: bridge
```
