### ISSUE TITLE
Cant receive confirmation Email

### ISSUE THREAD

**Issue by oregonpillow** [simple-login/app#652]
Trying to use linuxserver/swag for running an nginx server but I was surprised they didn't provide a template for SimpleLogin already. Tried creating my own .conf.

I keep getting 502 errors when I try connecting.￼

This is my setup, any help appreciated. 

docker-compose:
```
version: '3.3'
services:
    app:
        container_name: sl-app
        network_mode: lsio
        volumes:
            - '/home/debian/dockers/simplelogin/sl:/sl'
            - '/home/debian/dockers/simplelogin/sl/upload:/code/static/upload'
            - '/home/debian/dockers/simplelogin/simplelogin.env:/code/.env'
            - '/home/debian/dockers/simplelogin/dkim.key:/dkim.key'
            - '/home/debian/dockers/simplelogin/dkim.pub.key:/dkim.pub.key'
        ports:
            - '127.0.0.1:7777:7777'
        restart: always
        network_mode: sl-network
        image: 'simplelogin/app:3.4.0'
```

SWAG nginx proxy .conf:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name app.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app sl-app;
        set $upstream_port 7777;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
    }
}
```
